version: "1"
services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: morni
      POSTGRES_DB: morni
      POSTGRES_PASSWORD: morni
    volumes:
      - pgdata:/var/lib/posgresql/data

  redis:
    image: redis
    container_name: redis
    expose:
      - "6379"

  app:
    image: morni
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./:/morni
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - redis

volumes:
  pgdata:
